version: '3'

services:
  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DATABASE_PORT}:5432"
  app:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: ${PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: db
      DATABASE: ${DATABASE}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_ACCESS_SECRET:  ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CLIENT_URL_1: ${CLIENT_URL_1}
      CLIENT_URL_2: ${CLIENT_URL_2}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    stop_grace_period: 30s
    env_file:
      - .env
